name: Translate README

on:
    push:
        paths:
            - 'README.ru.md'
        branches:
            - main

jobs:
    process-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24.4.1'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run npm script
              run: npm run build

            - name: Check for changes
              id: verify-changed-files
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Commit and push changes
              if: steps.verify-changed-files.outputs.changed == 'true'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add .
                  git commit -m "Auto-update after README.ru.md changes [skip ci]"
                  git push
